const contentData = [
  {
    title: "Mountain Escape",
    description: "Peaceful views from the hills",
    genre: "Travel",
    likes: 1610,
    rating: 9.3,
    starred: 210,
    liked_by: [],
    starred_by: [],
    comments: [],
    thumbnail_url:
      "https://res.cloudinary.com/dbk7u2li2/image/upload/v1767695484/IMG_2677_ksugrv.jpg",
    stream_url: "http://localhost:8000/output.m3u8",
    is_live: true,
  },
  {
    title: "Quiet Morning Life",
    description: "A calm start to the day with positive thoughts",
    genre: "Life",
    likes: 1220,
    rating: 7.8,
    starred: 45,
    liked_by: [],
    starred_by: [],
    comments: [],
    thumbnail_url:
      "https://res.cloudinary.com/dbk7u2li2/image/upload/v1766843347/my_morning_routine_in_photos_-_wake_up_-_morning_thoughts_-_hydrate_-_cosy_up_%EF%B8%8F_-_caffeinate_-_breakfast___%EF%B8%8F_-_mindful_eating_-_affirmations_morningroutine_morning_breakfast_breakf_n0hdga.jpg",
    stream_url: "http://localhost:8000/output.m3u8",
    is_live: false,
  },
  {
    title: "Finding Purpose",
    description: "Simple habits that bring meaning to life",
    genre: "Life",
    likes: 230,
    rating: 8.2,
    starred: 60,
    liked_by: [],
    starred_by: [],
    comments: [],
    thumbnail_url:
      "https://res.cloudinary.com/dbk7u2li2/image/upload/v1766826426/purpose_jdhnrm.jpg",
    stream_url: "http://localhost:8000/output.m3u8",
    is_live: false,
  },
  {
    title: "Soft Aesthetic Room",
    description: "Warm lights, cozy corners, and calm vibes",
    genre: "Aesthetic",
    likes: 340,
    rating: 8.6,
    starred: 90,
    liked_by: [],
    starred_by: [],
    comments: [],
    thumbnail_url:
      "https://res.cloudinary.com/dbk7u2li2/image/upload/v1766843088/__tgrux5.jpg",
    stream_url: "http://localhost:8000/output.m3u8",
    is_live: false,
  },
  {
    title: "Minimal Desk Setup",
    description: "Clean workspace for better focus",
    genre: "Aesthetic",
    likes: 410,
    rating: 8.9,
    starred: 120,
    liked_by: [],
    starred_by: [],
    comments: [],
    thumbnail_url:
      "https://res.cloudinary.com/dbk7u2li2/image/upload/v1766843115/apple_imac_workspase_xoqmov.jpg",
    stream_url: "http://localhost:8000/output.m3u8",
    is_live: false,
  },
  {
    title: "Solo Travel Diaries",
    description: "Exploring new cities alone",
    genre: "Travel",
    likes: 520,
    rating: 9.1,
    starred: 180,
    liked_by: [],
    starred_by: [],
    comments: [],
    thumbnail_url:
      "https://res.cloudinary.com/dbk7u2li2/image/upload/v1766843180/Page_from_my_SD_trip_wvkni6.jpg",
    stream_url: "http://localhost:8000/output.m3u8",
    is_live: false,
  },

  {
    title: "Beach Walk Therapy",
    description: "Healing walks by the sea",
    genre: "Travel",
    likes: 480,
    rating: 8.8,
    starred: 160,
    liked_by: [],
    starred_by: [],
    comments: [],
    thumbnail_url:
      "https://res.cloudinary.com/dbk7u2li2/image/upload/v1766843066/__1_hupdrf.jpg",
    stream_url: "http://localhost:8000/output.m3u8",
    is_live: false,
  },
  {
    title: "Funny Cat ",
    description: "A playful cat causing chaos",
    genre: "Cartoon",
    likes: 900,
    rating: 9.0,
    starred: 300,
    liked_by: [],
    starred_by: [],
    comments: [],
    thumbnail_url:
      "https://res.cloudinary.com/dbk7u2li2/image/upload/v1766843264/__5_ea82er.jpg",
    stream_url: "http://localhost:8000/output.m3u8",
    is_live: false,
  },

  {
    title: "Mountain Ski Adventure",
    description:
      "Two friends enjoying an exciting ski adventure in the snowy mountains",
    genre: "Adventure",
    likes: 980,
    rating: 9.2,
    starred: 390,
    liked_by: [],
    starred_by: [],
    comments: [],
    thumbnail_url:
      "https://res.cloudinary.com/dbk7u2li2/image/upload/v1766843080/q07othxltr9cuy0zjfs1.jpg",
    stream_url: "http://localhost:8000/output.m3u8",
    is_live: false,
  },

  {
    title: "Lazy Sunday Life",
    description: "Relaxing and recharging at home",
    genre: "Life",
    likes: 260,
    rating: 8.1,
    starred: 75,
    liked_by: [],
    starred_by: [],
    comments: [],
    thumbnail_url:
      "https://res.cloudinary.com/dbk7u2li2/image/upload/v1766843186/Sunday_vibes___fresh_flowers_jdemvo.jpg",
    stream_url: "http://localhost:8000/output.m3u8",
    is_live: false,
  },
  {
    title: "Night City Aesthetic",
    description: "City lights and late-night walks",
    genre: "Aesthetic",
    likes: 370,
    rating: 8.7,
    starred: 130,
    liked_by: [],
    starred_by: [],
    comments: [],
    thumbnail_url:
      "https://res.cloudinary.com/dbk7u2li2/image/upload/v1766843102/__2_km375s.jpg",
    stream_url: "http://localhost:8000/output.m3u8",
    is_live: false,
  },
  {
    title: "Train Journey Memories",
    description: "Stories from long train rides",
    genre: "Travel",
    likes: 450,
    rating: 8.9,
    starred: 155,
    liked_by: [],
    starred_by: [],
    comments: [],
    thumbnail_url:
      "https://res.cloudinary.com/dbk7u2li2/image/upload/v1766843124/cute_train_journey_sunset_jkok80.jpg",
    stream_url: "http://localhost:8000/output.m3u8",
    is_live: false,
  },
  {
    title: "Cartoon School Life",
    description: "Funny moments from school days",
    genre: "Cartoon",
    likes: 780,
    rating: 8.8,
    starred: 260,
    liked_by: [],
    starred_by: [],
    comments: [],
    thumbnail_url:
      "https://res.cloudinary.com/dbk7u2li2/image/upload/v1766843096/__3_ccb3re.jpg",
    stream_url: "http://localhost:8000/output.m3u8",
    is_live: false,
  },
  {
    title: "Dreamy Aesthetic Clouds",
    description: "Slow-moving clouds and soft music",
    genre: "Aesthetic",
    likes: 390,
    rating: 8.6,
    starred: 140,
    liked_by: [],
    starred_by: [],
    comments: [],
    thumbnail_url:
      "https://res.cloudinary.com/dbk7u2li2/image/upload/v1766843093/__4_ziymgj.jpg",
    stream_url: "http://localhost:8000/output.m3u8",
    is_live: false,
  },
];

module.exports = { contentData };
